# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Witaj w moim pierwszym Azure Pipeline!
  displayName: 'Moj pierwszy krok'

- script: node --version
  displayName: 'Sprawdz wersje Node.js'  

- script: npm ci
  displayName: 'Install dependencies'

- script: npx playwright install --with-deps chromium
  displayName: 'Install Chromium' 

- script: npm run build
  displayName: 'Build Next.js application'